#%RAML 0.8
---
title: PROJECT 1 API
baseUri: https://localhost/api/{version}
version: v1

/users:
	get:
	put:
	post:
	
	
	/{id}
		get:
			queryParameters:
				name:
		put:
		post:
	
		
/organizations:

/facts:

/observations:

/sensors:
	/{id}
		get:
			queryParameters:
				name:
				description:
				type:
				visibility:
		put:
		post: